version: '3'
services:
  web:
    build: 
        context: ./app
    ports:
      - "8081:5000"
    volumes:
      - ./app:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
  mqtrw:
    build: 
        context: ./mqttrw
 