version: '3'
services:
  web:
    build: 
        context: ./web
    ports:
      - "8081:5000"
    volumes:
      - ./web:/code
    environment:
      - FLASK_DEBUG="true"
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - /var/tmp/redis:/data
  mqtrw:
    build: 
        context: ./mqttrw
    depends_on:
      - redis
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
  prometheus:
    build:
        context: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web
    volumes:
      - /var/tmp/prometheus:/prometheus
  grafana:
    build:
      context: ./grafana
    ports:
     - '3000:3000'
  mosquitto:
    build: 
        context: ./mosquitto
    ports:
      - 1883:1883

