version: '3'
services:
  web:
    build: 
        context: ./web
    ports:
      - "8081:5000"
    volumes:
      - ./web:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
  mqtrw:
    build: 
        context: ./mqttrw
  prometheus:
    build:
        context: ./prometheus
    ports:
      - "9090:9090"
