{
 "title": "testcooler",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "actual_temperature{device_name=\"testcooler\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "target_temperature{device_name=\"testcooler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days of fermentation",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_day{device_name=\"testcooler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bubble count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bubble_count{device_name=\"testcooler\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}