{
 "title": "fermctrlvar",
 "time": { "from": "now-1w", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "device", "query": "blank" }
  ]
 },
 "panels": [
  {
   "title": "Temperature actual and target for $device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "actual_temperature{device_name=\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "target_temperature{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cooler and heater average time in use over 1 h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(cooler_on{device_name=\"$device\"}[1h])*100",
     "legendFormat": "cooler_on_1h_avg"
    },
    {
     "expr": "avg_over_time(heater_on{device_name=\"$device\"}[1h])*100",
     "legendFormat": "heater_on_1h_avg"
    }
   ]
  },
  {
   "title": "Days of fermentation for $device",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_day{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bubble count for $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bubble_count{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}